### ISSUE TITLE
selector parse error

### ISSUE THREAD

**Issue by myamolane** [johanholmerin/style9#41]
I found that style9 will try to parse selector name from each decl's parent
https://github.com/johanholmerin/style9/blob/master/src/process-css.js#L94
`const selectors = parseSelector(rule.parent);`

but there are some exception, like this one
`@-ms-viewport {
   width: device-width;
}
`
PostCSS recognizes `width: device-width` as a declaration, but the type of this declaration’s parent is 'atrule'. There is no property 'selector' in type 'atrule', and this will make postcss-selector-parser generate exception.

As far as I know, @-ms-viewport is a deprecated API but some UI component repository still use it for some reasons.

`
[webpack-cli] TypeError: Cannot read property 'valueOf' of undefined
    at tokenize (/Users/cosimo/code/style9/node_modules/postcss-selector-parser/dist/tokenize.js:93:23)
    at new Parser (/Users/cosimo/code/style9/node_modules/postcss-selector-parser/dist/parser.js:130:41)
    at Processor._root (/Users/cosimo/code/style9/node_modules/postcss-selector-parser/dist/processor.js:55:18)
    at Processor._runSync (/Users/cosimo/code/style9/node_modules/postcss-selector-parser/dist/processor.js:102:21)
    at Processor.transformSync (/Users/cosimo/code/style9/node_modules/postcss-selector-parser/dist/processor.js:173:17)
    at parseSelector (/Users/cosimo/code/style9/src/process-css.js:41:47)
    at /Users/cosimo/code/style9/src/process-css.js:94:23
    at Array.forEach (<anonymous>)
    at extractDecls (/Users/cosimo/code/style9/src/process-css.js:93:9)
    at sortPseudo (/Users/cosimo/code/style9/src/process-css.js:149:27)
    at LazyResult.run (/Users/cosimo/code/style9/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.sync (/Users/cosimo/code/style9/node_modules/postcss/lib/lazy-result.js:274:26)
    at LazyResult.stringify (/Users/cosimo/code/style9/node_modules/postcss/lib/lazy-result.js:298:10)
    at LazyResult.get (/Users/cosimo/code/style9/node_modules/postcss/lib/lazy-result.js:379:19)
    at Style9Plugin._processFiles (/Users/cosimo/code/style9/webpack/index.js:52:18)
    at /Users/cosimo/code/style9/webpack/index.js:33:16
`

**Comment by johanholmerin** [comment]
Fixed in 0.10.5
